# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
jobs:
  save-hello-output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: SaveHello
          command: |
            echo "Hello" > output.txt
      - persist_to_workspace:
          root: .
          paths: 
            - "output.txt"
  print-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: World
          command: |
            echo World
            echo $MY_NAME

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - print-hello
      - print-world:
          requires:
          - print-hello
